import React from 'react'

import Head from 'next/head'
import { Roboto_Mono } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import fs from 'fs'
import path from 'path'
import matter  from 'gray-matter'
import Name from '@/components/Name'
import ProjectList from '@/components/ProjectList'
import ProjectPreview from '@/components/ProjectPreview'
import Pepes from '@/components/Pepes'

const inter = Roboto_Mono({ subsets: ['latin']})

export default function Home({posts}) {
  const [preview, setPreview] = React.useState(null);

  const updatePreview = (data) => {
    setPreview(data);
  };

  return (
    <>
      <Head>
        <title>David</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`${styles.window}`}>
          <Pepes />
          <Name />
          <ProjectList posts={posts} updatePreview={updatePreview}/>
          <ProjectPreview preview={preview}/>
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const files = fs.readdirSync(path.join('posts'));

  const posts = files.map(filename => {
    const slug = filename.replace('.md','')
    const mdWithMeta = fs.readFileSync(path.join('posts', filename), 'utf-8')
    const {data: frontmatter} = matter(mdWithMeta)
    
    return {
      slug, frontmatter
    }
  })
  return {
    props: {
      posts: posts
    }
  }
}



